name: DKBansCommandOnBan
author: Davide Wietlisbach
version: ${project.version}
api-version: 1.13
depend: [DKBans]

main: ch.dkrieger.bansystem.extension.commandsonban.bukkit.DKBansCommandsOnBanExtension
